import ThemeClient from "@/components/ThemeClient";
import { GlobalStyle } from "@/styles/global";
import type { Metadata } from "next";
import StyledComponentsRegistry from "./registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeClient>
        <GlobalStyle />
        <body>{children}</body>
      </ThemeClient>
    </html>
  );
}
